import { FOODS, KNOWN_KEYS, nutritionFor } from '../data/foods.mjs';
const MODEL='gpt-5-mini';
const NUMBER_WORDS={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10};
const FILLER=new Set(['i','ate','had','have','for','breakfast','lunch','dinner','and','with','plus','a','an','the','de','y','con','comi','comí','desayuno','comida','cena']);
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(body));}
function norm(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s.]/g,' ').replace(/\s+/g,' ').trim();}
function parseQty(t){if(!t)return 1;if(/^\d+(?:\.\d+)?$/.test(t))return Number(t);return NUMBER_WORDS[t]||1;}
function esc(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function hydrationParse(text){
 const t=norm(text);
 if(!/\b(water|agua)\b/.test(t))return null;
 let liters=0;
 let m=t.match(/(\d+(?:\.\d+)?)\s*(?:liters?|litres?|l)\b/);if(m)liters=Number(m[1]);
 if(!liters){m=t.match(/(\d+(?:\.\d+)?)\s*(?:ml|milliliters?|millilitres?)\b/);if(m)liters=Number(m[1])/1000;}
 if(!liters){m=t.match(/(\d+(?:\.\d+)?)\s*(?:cups?|vasos?)\b/);if(m)liters=Number(m[1])*0.24;}
 if(!liters)return null;
 return{type:'hydration',name:`Water (${+liters.toFixed(2)} L)`,liters:+liters.toFixed(2),note:'Water added to today’s hydration total.',answer:'',source:'local-hydration',model:'deterministic-local'};
}
function deterministicFoodParse(text){
 const input=norm(text),candidates=[],qtyWords=Object.keys(NUMBER_WORDS).join('|');
 for(const key of KNOWN_KEYS)for(const rawAlias of FOODS[key].aliases){const alias=norm(rawAlias);const re=new RegExp(`(?:\\b(\\d+(?:\\.\\d+)?|${qtyWords})\\s+)?\\b${esc(alias)}\\b`,'g');let m;while((m=re.exec(input)))candidates.push({key,alias,quantity:parseQty(m[1]),hasQty:!!m[1],start:m.index,end:re.lastIndex});}
 candidates.sort((a,b)=>(Number(b.hasQty)-Number(a.hasQty))||a.start-b.start||(b.end-b.start)-(a.end-a.start));
 const matches=[],occupied=[];for(const c of candidates){if(occupied.some(([a,b])=>c.start<b&&c.end>a))continue;matches.push(c);occupied.push([c.start,c.end]);}
 if(!matches.length)return null;matches.sort((a,b)=>a.start-b.start);
 let leftover=input;for(const m of [...matches].sort((a,b)=>b.start-a.start))leftover=leftover.slice(0,m.start)+' '+leftover.slice(m.end);
 const unknown=norm(leftover).split(' ').filter(Boolean).filter(w=>!FILLER.has(w)&&!NUMBER_WORDS[w]&&!/^\d+(?:\.\d+)?$/.test(w));if(unknown.length)return null;
 const items=matches.map(m=>({key:m.key,quantity:m.quantity,...nutritionFor(m.key,m.quantity,null,null)}));
 const totals=items.reduce((a,i)=>({calories:a.calories+i.calories,protein_g:a.protein_g+i.protein_g,carbs_g:a.carbs_g+i.carbs_g,fat_g:a.fat_g+i.fat_g}),{calories:0,protein_g:0,carbs_g:0,fat_g:0});
 return{type:'food',name:foodNameFromItems(items),items,calories:Math.round(totals.calories),protein_g:+totals.protein_g.toFixed(1),carbs_g:+totals.carbs_g.toFixed(1),fat_g:+totals.fat_g.toFixed(1),note:'Calculated from local reference foods; no AI estimate used.',answer:'',source:'local-reference',model:'deterministic-local'};
}
function workoutCalories(met,minutes,weightKg){const m=Number(met)||0,min=Number(minutes)||0,kg=Number(weightKg)||0;if(!m||!min||!kg)return 0;return Math.max(0,Math.round(m*3.5*kg/200*min));}
function foodNameFromItems(items=[]){return items.map(i=>{const q=Number(i.quantity)||0;const label=i.label||i.key||'food';return q>0?`${q} ${label}${q===1?'':'s'}`:label;}).join(' + ')||'Meal';}
function isGenericMealName(name=''){return /^(meal|food|breakfast|lunch|dinner|snack|my meal|mixed meal)$/i.test(String(name).trim());}
function estimateRepDuration(text){const t=norm(text),exerciseWords='push ups?|pushups?|crunches?|sit ups?|situps?|squats?|lunges?|burpees?|high knees?|jumping jacks?|pull ups?|pullups?|dips?|mountain climbers?|reps?',re=new RegExp(`\\b(\\d{1,4})\\s+(?:${exerciseWords})\\b`,'g');let m,totalReps=0,groups=0;while((m=re.exec(t))){totalReps+=Number(m[1])||0;groups++;}if(!totalReps)return 0;const activeSeconds=totalReps*2.5,transitionSeconds=Math.max(0,groups-1)*30,restSeconds=groups*20;return Math.max(3,Math.min(45,Math.round((activeSeconds+transitionSeconds+restSeconds)/60)));}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'POST only'});try{
 const body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{}),text=String(body.text||'').trim().slice(0,1200),user=String(body.user||'User').slice(0,40),context=body.context&&typeof body.context==='object'?body.context:{};if(!text)return json(res,400,{error:'Missing text'});
 const hydration=hydrationParse(text);if(hydration)return json(res,200,hydration);
 const direct=deterministicFoodParse(text);if(direct)return json(res,200,direct);
 const apiKey=(process.env.OPENAI_API_KEY||process.env.OPEN_API_KEY||process.env.open_api_key||process.env.openai_api_key||'').trim();if(!apiKey)return json(res,500,{error:'OpenAI API key is not configured for this deployment'});
 const catalog=KNOWN_KEYS.map(k=>`${k}: ${FOODS[k].label} (${FOODS[k].per})`).join('; ');
 const system=`You are a precise fallback parser for a private nutrition and workout logging app. ONLY parse the CURRENT user message. Never import foods, workouts, or quantities from previous messages. User: ${user}. Known local food keys: ${catalog}. For plain water/agua, classify as hydration and return liters consumed; do not classify plain water as food. For food/drink, split only the current message into ingredients. Preserve every stated food and quantity. Match a known key when appropriate. Generic tortilla means corn_tortilla_6in unless flour/harina is explicit. Unknown prepared foods use key 'unknown' and estimate only that item conservatively. Give the meal a descriptive name based only on the foods in this message; never return just "meal" if the foods are known. For workouts, identify the activity, duration in minutes if explicitly stated, and choose a conservative MET value representing the overall session intensity. If duration is not stated, set duration_min=0. Do not invent duration; the server may derive a conservative duration from explicit rep counts. For general questions, answer concisely. Current profile context: ${JSON.stringify(context)}.`;
 const response=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:system},{role:'user',content:text}],response_format:{type:'json_schema',json_schema:{name:'fitness_parse',strict:true,schema:{type:'object',additionalProperties:false,properties:{type:{type:'string',enum:['food','workout','hydration','question']},name:{type:'string'},items:{type:'array',items:{type:'object',additionalProperties:false,properties:{key:{type:'string',enum:[...KNOWN_KEYS,'unknown']},label:{type:'string'},quantity:{type:'number',minimum:0},grams:{type:'number',minimum:0},ml:{type:'number',minimum:0},estimated_calories:{type:'number',minimum:0},estimated_protein_g:{type:'number',minimum:0},estimated_carbs_g:{type:'number',minimum:0},estimated_fat_g:{type:'number',minimum:0}},required:['key','label','quantity','grams','ml','estimated_calories','estimated_protein_g','estimated_carbs_g','estimated_fat_g']}},duration_min:{type:'number',minimum:0},met:{type:'number',minimum:0,maximum:20},liters:{type:'number',minimum:0},note:{type:'string'},answer:{type:'string'}},required:['type','name','items','duration_min','met','liters','note','answer']}}}})});
 const data=await response.json();if(!response.ok)return json(res,response.status,{error:data?.error?.message||'AI request failed'});const raw=data?.choices?.[0]?.message?.content;if(!raw)return json(res,502,{error:'AI returned no content'});const parsed=JSON.parse(raw);
 if(parsed.type==='hydration')return json(res,200,{type:'hydration',name:parsed.name||'Water',liters:+parsed.liters||0,note:parsed.note||'Water added to today’s hydration total.',answer:'',source:'ai-hydration',model:MODEL});
 if(parsed.type==='workout'){const weightKg=Number(context.weight_kg)||0,explicitDuration=Number(parsed.duration_min)||0,derivedDuration=explicitDuration?0:estimateRepDuration(text),duration=explicitDuration||derivedDuration,burn=workoutCalories(parsed.met,duration,weightKg),noteParts=[];if(parsed.note)noteParts.push(parsed.note);if(!weightKg)noteParts.push('Add body weight in Profile to estimate calories burned.');else if(!duration)noteParts.push('Add workout duration or rep counts to estimate calories burned.');else if(derivedDuration)noteParts.push(`Duration estimated at about ${derivedDuration} min from the rep counts; calorie burn uses ${parsed.met} MET and ${weightKg} kg body weight.`);else noteParts.push(`Estimated using ${parsed.met} MET, ${duration} min, and ${weightKg} kg body weight.`);return json(res,200,{type:'workout',name:parsed.name||text,duration_min:duration,duration_estimated:!!derivedDuration,met:+parsed.met||0,calories_burned:burn,note:noteParts.join(' '),answer:'',source:derivedDuration?'met-rep-duration-estimate':'met-estimate',model:MODEL});}
 if(parsed.type!=='food')return json(res,200,{...parsed,calories:0,protein_g:0,carbs_g:0,fat_g:0,source:'ai-parser',model:MODEL});
 const resolved=parsed.items.map(item=>item.key!=='unknown'?{...item,...nutritionFor(item.key,item.quantity,item.grams,item.ml)}:{...item,calories:Math.round(item.estimated_calories||0),protein_g:+(item.estimated_protein_g||0).toFixed(1),carbs_g:+(item.estimated_carbs_g||0).toFixed(1),fat_g:+(item.estimated_fat_g||0).toFixed(1),source:'ai-estimate'}),totals=resolved.reduce((a,i)=>({calories:a.calories+(i.calories||0),protein_g:a.protein_g+(i.protein_g||0),carbs_g:a.carbs_g+(i.carbs_g||0),fat_g:a.fat_g+(i.fat_g||0)}),{calories:0,protein_g:0,carbs_g:0,fat_g:0}),sources=[...new Set(resolved.map(i=>i.source))],finalName=isGenericMealName(parsed.name)?foodNameFromItems(resolved):(parsed.name||foodNameFromItems(resolved));return json(res,200,{type:'food',name:finalName,items:resolved,calories:Math.round(totals.calories),protein_g:+totals.protein_g.toFixed(1),carbs_g:+totals.carbs_g.toFixed(1),fat_g:+totals.fat_g.toFixed(1),note:parsed.note,answer:parsed.answer,source:sources.length===1?sources[0]:'mixed',model:MODEL});
}catch(error){console.error(error);return json(res,500,{error:'Unable to process entry'});}}
